# Generated by Django 5.2 on 2025-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('fonte_dos_dados', models.TextField(verbose_name='Fonte dos Dados')),
                ('utilizacao', models.TextField(verbose_name='Utilização')),
                ('documentacao', models.FileField(upload_to='documentacao/', verbose_name='Documentação (PDF)')),
                ('data_atualizacao', models.DateField(verbose_name='Data da Atualização')),
            ],
        ),
    ]
