# Generated by Django 5.2 on 2025-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Dashboard'),
        ),
    ]
