# Generated by Django 5.2 on 2025-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_dashboard_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='documentacao',
            field=models.FileField(null=True, upload_to='documentacao/', verbose_name='Documentação (PDF)'),
        ),
    ]
