# Generated by Django 5.2 on 2025-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_alter_dashboard_documentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='documentacao',
            field=models.FileField(blank=True, null=True, upload_to='documentacao/', verbose_name='Documentação (PDF)'),
        ),
    ]
